### ISSUE TITLE
lammps.sh is incorrectly labeled, it's gromacs.sh

### ISSUE THREAD

**Issue by CatherineMoulder** [WSUChem537/General#1]
I believe this is what we need instead.

#!/bin/bash
#SBATCH --partition=kamiak
#SBATCH -J boehmite.KCl
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=20
#SBATCH --threads-per-core=1
#SBATCH --time=50:00:00

module load intel/xe_2016_update2
module load lammps

prefix="$SLURM_JOB_NAME"
srun -n $SLURM_NTASKS lmp -i $prefix.in -echo screen -log none >> $prefix.out

**Comment by WSUChem537** [comment]
removed this file and put in new file into lammps directory under General
